---
title: "Ecker 2017: Downsampling experiment"
author: "C.A.Kapourani"
output: 
  html_notebook:
    df_print: paged
    highlight: haddock
    number_sections: yes
    theme: cerulean
    toc: yes
---

```{r set_global_options, cache=FALSE, results='hide', echo=FALSE, warning=FALSE, message=FALSE}
library('knitr')
knitr::opts_chunk$set(dpi = 75, warning = FALSE, message = FALSE)
```

# Load libraries and settings
```{r}
# Get density of points in 2 dimensions.
# @param x A numeric vector.
# @param y A numeric vector.
# @param n Create a square n by n grid to compute density.
# @return The density within each square.
get_density <- function(x, y, ...) {
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}

suppressPackageStartupMessages(library(scMET))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(viridis))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(scattermore))

data_dir <- "~/datasets/scMET_ms/ecker2017/downsampling/data/"
out_dir <- "~/datasets/scMET_ms/ecker2017/downsampling/analysis/"
if (!dir.exists(out_dir)) {dir.create(out_dir, recursive = TRUE)}

## Options ##
opts <- list()
opts$anno <- c(
  "Distal H3K27ac" = "distal_H3K27ac_cortex",
  "H3K4me1" = "H3K4me1_cortex",
  "Promoters" = "prom_2000_2000"
)
opts$rep <- paste0("rep", 1:5)
opts$cells <- c(20, 50, 100, 200, 424)
opts$cells_str <- c("Cells_20", "Cells_50", "Cells_100", "Cells_200", "Cells_424")
opts$lor_str <- c("LOR_20", "LOR_50", "LOR_100", "LOR_200")
opts$val_thresh <- 1e-6
```

## Load fitted objects
```{r}
dt_scmet = dt_mle <- list()
for (rep in opts$rep) {
  dt_scmet_rep = dt_mle_rep <- list()
  for (c in 1:length(opts$cells)) {
    # scMET VB
    dt_scmet_rep[[c]] <- opts$anno %>%
      map(~ fread(sprintf("%s/%s/%s_Inh_%s_vb.txt.gz", data_dir, 
                          rep, ., opts$cells[c]))) %>% rbindlist %>%
      .[,c("mu_median", "gamma_median", "epsilon_median", "Feature", "anno")] %>%
      setnames(c("mu_median", "gamma_median", "epsilon_median"), 
               c("mu", "gamma", "epsilon")) %>%
      .[, gamma := ifelse(gamma > opts$val_thresh & 
                            gamma < 1 - opts$val_thresh, gamma, 
                          ifelse(gamma < opts$val_thresh, 
                                 opts$val_thresh, 1 - opts$val_thresh))] %>%
      .[, mu := ifelse(mu > opts$val_thresh & 
                         mu < 1 - opts$val_thresh, mu, 
                          ifelse(mu < opts$val_thresh, 
                                 opts$val_thresh, 1 - opts$val_thresh))] %>%
      melt(id.vars = c("Feature", "anno")) %>%
      .[,inference := "scMET"] %>% 
      .[,down_cells := opts$cells_str[c]] %>% .[, replicate := rep]
    
    # MLE
    dt_mle_rep[[c]] <- opts$anno %>%
      map(~ fread(sprintf("%s/%s/%s_Inh_%s_mle.txt.gz", data_dir, 
                          rep, ., opts$cells[c]))) %>% rbindlist %>%
      .[,c("mu", "gamma", "Feature", "anno")] %>%
      .[, gamma := ifelse(gamma > opts$val_thresh & 
                            gamma < 1 - opts$val_thresh, gamma, 
                          ifelse(gamma < opts$val_thresh, 
                                 opts$val_thresh, 1 - opts$val_thresh))] %>%
      .[, mu := ifelse(mu > opts$val_thresh & 
                         mu < 1 - opts$val_thresh, mu, 
                          ifelse(mu < opts$val_thresh, 
                                 opts$val_thresh, 1 - opts$val_thresh))] %>%
      melt(id.vars = c("Feature", "anno")) %>%
      .[,inference := "BB MLE"] %>% 
      .[,down_cells := opts$cells_str[c]] %>% .[, replicate := rep]
  }
  dt_scmet[[rep]] <- rbindlist(dt_scmet_rep)
  dt_mle[[rep]] <- rbindlist(dt_mle_rep)
}
dt_scmet <- rbindlist(dt_scmet)
dt_mle <- rbindlist(dt_mle)

dt_joint <- rbind(dt_scmet, dt_mle)
rm(dt_scmet_rep, dt_mle_rep, rep, c)
```

## Downsampling LOR performance
```{r, fig.width=5, fig.height=2}
# Create wide data.table
to_plot_fig <- dt_joint[variable == "gamma"] %>% .[, variable := NULL] %>%
  dcast(Feature + anno + inference + replicate ~ down_cells) %>% na.omit()
# Now compute LORs
opts$lor_cells <- c("20", "50", "100", "200")
for (c in 1:length(opts$cells_str[1:4])) {
  to_plot_fig[, opts$lor_cells[c] := scMET:::.compute_log_odds_ratio(
    get(opts$cells_str[5]), get(opts$cells_str[c]))]
}
to_plot_fig <- to_plot_fig %>% .[, opts$cells_str := NULL]

tmp <- to_plot_fig %>%
  melt(id.vars = c("Feature", "anno", "inference", "replicate")) %>%
  .[, variable := factor(variable)]
tmp <- tmp[, .(value = mean(abs(value))), 
           by = c("anno", "inference", "variable", "replicate")]
tmp$inference <- factor(tmp$inference, levels = c("BB MLE", "scMET"), 
                        labels = c("BB MLE", "scMET"))
tmp$anno <- factor(tmp$anno, levels = c("prom_2000_2000", "distal_H3K27ac_cortex", 
                                        "H3K4me1_cortex"),
                   labels = c("Promoters", "Distal H3K27ac", "H3K4me1"))

p <- ggplot(tmp, aes(x = factor(variable), y = value, fill = inference)) +
  geom_jitter(size = 3, width = 0.1, height = .001, shape = 21) +
  facet_wrap(~anno, scales = "free") +
  scale_fill_manual(values = c("#999999", "#E69F00", "#56B4E9")) +
  scale_y_continuous(breaks = scales::pretty_breaks(5)) +
  scale_color_manual(values = c("#999999", "#E69F00", "#56B4E9")) +
  labs(title = NULL, x = "Number of cells", 
       y = expression(paste("LOR (", gamma[all], ", ", 
                            gamma[downsampled], " )")), fill = "Model") +
  theme_classic() +
  theme(
      legend.position = c(0.93, 0.8),
      plot.tag = element_text(color = "black", face = "bold", size = rel(1.6)),
      legend.title = element_text(color = "black", size = rel(1)),
      legend.text = element_text(color = "black", size = rel(1.1)),
      strip.text = element_text(color = "black", size = rel(1.1)),
      axis.text = element_text(color = "black", size = rel(0.9)),
      axis.title = element_text(color = "black", size = rel(1.1))
    )
print(p)
pdf(file = paste0(out_dir, "ecker_downsampling_lor.pdf"), width = 10, height = 3.6, useDingbats = FALSE)
p
dev.off()
```


# Scatter plots from one replication
## Load fitted objects
```{r}
r <- 1
dt_scmet = dt_mle <- list()
for (c in 1:length(opts$cells)) {
  # scMET VB
  dt_scmet[[c]] <- opts$anno %>%
    map(~ fread(sprintf("%s/%s/%s_Inh_%s_vb.txt.gz", data_dir, 
                        opts$rep[r], ., opts$cells[c]))) %>% rbindlist %>%
    .[,c("mu_median", "gamma_median", "epsilon_median", "Feature", "anno")] %>%
    setnames(c("mu_median", "gamma_median", "epsilon_median"), 
             c("mu", "gamma", "epsilon")) %>%
    .[, gamma := ifelse(gamma > opts$val_thresh & 
                          gamma < 1 - opts$val_thresh, gamma, 
                        ifelse(gamma < opts$val_thresh, 
                               opts$val_thresh, 1 - opts$val_thresh))] %>%
    .[, mu := ifelse(mu > opts$val_thresh & mu < 1 - opts$val_thresh, mu, 
                        ifelse(mu < opts$val_thresh, 
                               opts$val_thresh, 1 - opts$val_thresh))] %>%
    melt(id.vars = c("Feature", "anno")) %>%
    .[,inference := "scMET"] %>% .[,down_cells := opts$cells_str[c]]
  
  # MLE
  dt_mle[[c]] <- opts$anno %>%
    map(~ fread(sprintf("%s/%s/%s_Inh_%s_mle.txt.gz", data_dir, 
                        opts$rep[r], ., opts$cells[c]))) %>% rbindlist %>%
    .[,c("mu", "gamma", "Feature", "anno")] %>%
    .[, gamma := ifelse(gamma > opts$val_thresh & 
                          gamma < 1 - opts$val_thresh, gamma, 
                        ifelse(gamma < opts$val_thresh, 
                               opts$val_thresh, 1 - opts$val_thresh))] %>%
    .[, mu := ifelse(mu > opts$val_thresh & mu < 1 - opts$val_thresh, mu, 
                        ifelse(mu < opts$val_thresh, 
                               opts$val_thresh, 1 - opts$val_thresh))] %>%
    melt(id.vars = c("Feature", "anno")) %>%
    .[,inference := "BB MLE"] %>% .[,down_cells := opts$cells_str[c]]
}
dt_scmet <- rbindlist(dt_scmet)
dt_mle <- rbindlist(dt_mle)

# All data wide format
dt_scmet_all_wide <- dt_scmet %>%
  dcast(Feature+anno+variable+inference~down_cells) %>% na.omit()
dt_mle_all_wide <- dt_mle %>%
  dcast(Feature+anno+variable+inference~down_cells) %>% na.omit()
dt_joint_wide <- rbind(dt_scmet_all_wide, dt_mle_all_wide)

rm(dt_scmet_all_wide, dt_mle_all_wide, c, r)
```


## Scatter plots all genomic contexts
```{r, fig.width=5.5, fig.height=2.7}
for (an in 1:length(opts$anno)) {
  to_plot_fig <- dt_joint_wide[variable == "gamma" & anno == opts$anno[an]] %>% 
    .[, c("Feature", "inference", "Cells_20", "Cells_50", 
          "Cells_200", "Cells_424")] %>%
    setnames(c("Cells_20", "Cells_50", "Cells_200"), 
             c("20 cells", "50 cells", "200 cells"))
  to_plot_fig$inference <- factor(to_plot_fig$inference, 
                                  levels = c("scMET", "BB MLE"), 
                                  labels = c("scMET", "BB MLE"))
  
  to_plot_fig <- to_plot_fig %>% 
    melt(id.vars = c("Feature", "inference", "Cells_424"))
  to_plot_fig <- to_plot_fig[, density := get_density(get(tail(opts$cells_str, 1)), 
                                                      value, n = 100), by = "variable"]
  
  gg_mle <- ggplot(to_plot_fig[inference == "BB MLE"]) + 
    geom_scattermore(aes(get(tail(opts$cells_str, 1)), value, color = density), 
                     pointsize = 2.4) +
    facet_wrap(~variable, scales = "free", ncol = 4) +
    labs(x = expression(paste("BB MLE ", gamma, " (all 424 cells)")), 
         y = expression(paste("BB MLE ", gamma, " downsampled")),
         title = names(opts$anno[an])) +
    geom_abline(slope = 1, intercept = 0, linetype = "solid") +
    scale_fill_viridis() + scale_color_viridis() + theme_classic() + 
    theme(
      legend.position = "none",
      legend.title = element_blank(),
      plot.title = element_text(hjust = 0.5, color = "black", 
                                face = "bold", size = rel(1.3)),
      plot.tag = element_text(color = "black", face = "bold", size = rel(1.6)),
      legend.text = element_text(color = "black", size = rel(1.1)),
      strip.text = element_text(color = "black", size = rel(1.1)),
      axis.text = element_text(color = "black", size = rel(0.6)),
      axis.title = element_text(color = "black", size = rel(1))
    ) + xlim(c(0, 1)) + ylim(0, 1) 
  
  gg_scmet <- ggplot(to_plot_fig[inference == "scMET"]) + 
    geom_scattermore(aes(get(tail(opts$cells_str, 1)), value, color = density), 
                     pointsize = 2.4) +
    facet_wrap(~variable, scales = "free", ncol = 4) +
    labs(x = expression(paste("scMET ", gamma, " (all 424 cells)")), 
         y = expression(paste("scMET ", gamma, " downsampled"))) +
    geom_abline(slope = 1, intercept = 0, linetype = "solid") +
    scale_fill_viridis() + scale_color_viridis() + theme_classic() + 
    theme(
      legend.position = "none",
      legend.title = element_blank(),
      plot.tag = element_text(color = "black", face = "bold", size = rel(1.6)),
      legend.text = element_text(color = "black", size = rel(1.1)),
      strip.text = element_text(color = "black", size = rel(1.1)),
      axis.text = element_text(color = "black", size = rel(0.6)),
      axis.title = element_text(color = "black", size = rel(1))
    ) + xlim(c(0, 1)) + ylim(0, 1) 
  
  print(cowplot::plot_grid(gg_mle, gg_scmet, nrow = 2))
  
  pdf(file = paste0(out_dir, "ecker_downsampling_scatter_", opts$anno[an], ".pdf"), 
      width = 8, height = 5, useDingbats = FALSE)
  plot(cowplot::plot_grid(gg_mle, gg_scmet, nrow = 2))
  dev.off()
}
```
