---
title: "Robustness of parameter estimates for varying CpG coverage and cells"
author: "C.A. Kapourani & R. Argelaguet"
output: 
  html_notebook: 
    highlight: haddock
    theme: cerulean
    number_sections: true
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, results = "hide")
```


# Initialise params
```{r}
library(scMET)
library(data.table)
library(matrixStats)
library(coda)
library(ggpubr)
library(purrr)
set.seed(1234)

data_dir <- "~/datasets/scMET_ms/synthetic/diff_var/data/"
out_dir <- "~/datasets/scMET_ms/synthetic/robustness/"
if (!dir.exists(out_dir)) {dir.create(out_dir, recursive = TRUE)}

opts <- list()
opts$rep <- seq(1, 5)
opts$N_feat <- 300
opts$N_cells <- c(50, 200)
opts$N_cpgs <- c(8, 15)
opts$OR_change_gamma <- 2
```

## Load fitted objects and perform MLE
```{r}
compute_cpg <- function(x) {
  x_i <- c()
  for (i in x) {
    if (i < 5) {
      x_i <- c(x_i, "3_4")
    } else if (i < 7) {
      x_i <- c(x_i, "5_6")
    } else if (i < 9) {
      x_i <- c(x_i, "7_8")
    } else {
      x_i <- c(x_i, ">8")
    }
  }
  return(x_i)
}

summary_stats <- data.table(cells = numeric(), features = numeric(), 
                            cpgs = numeric(), feature_name = character(), 
                            gamma_true = numeric(), gamma_median = numeric(), 
                            gamma_sd = numeric(), epsilon_median = numeric(), 
                            epsilon_sd = numeric(), mu_true = numeric(), 
                            mu_median = numeric(), mu_sd = numeric(),
                            gamma_mle = numeric(), mu_mle = numeric(), 
                            cpg_cov = numeric(), cpg_bin = character())
for (r in opts$rep) {
  for (cpg in opts$N_cpgs) {
    for (c in opts$N_cells) {
      dt <- readRDS(file = paste0(data_dir, "rep", r, "/", 
                                  "scmet_ORgamma", opts$OR_change_gamma, 
                                  "_feat", opts$N_feat, 
                                  "_cells", c, "_cpgs", cpg, "_mcmcFALSE.rds"))
      fit_obj <- dt[[paste0("scmet_A")]]
      sim_dt <- dt$sim_dt[[paste0("scmet_dt_A")]]
      
      mle <- sim_dt$Y[, bb_mle(cbind(total_reads, met_reads))[c("gamma", "mu")], 
                      by = c("Feature")]
      summary_stats <- rbind(summary_stats,
          data.table(cells = c,
                     features = opts$N_feat,
                     cpgs = cpg,
                     feature_name = fit_obj$feature_names,
                     # gamma
                     gamma_true = sim_dt$theta_true$gamma,
                     gamma_median = colMedians(fit_obj$posterior$gamma),
                     gamma_sd = apply(fit_obj$posterior$gamma, 2, sd),
                     # epsilon
                     epsilon_median = colMedians(fit_obj$posterior$epsilon),
                     epsilon_sd = apply(fit_obj$posterior$epsilon, 2, sd),
                     # mu
                     mu_true = sim_dt$theta_true$mu,
                     mu_median = colMedians(fit_obj$posterior$mu),
                     mu_sd = apply(fit_obj$posterior$mu, 2, sd),
                     # MLE estimates
                     gamma_mle = mle$gamma,
                     mu_mle = mle$mu, 
                     # CpG coverage per feature
                     cpg_cov = sim_dt$Y[, median(total_reads), 
                                        by = "Feature"]$V1,
                     cpg_bin = compute_cpg(sim_dt$Y[, median(total_reads), 
                                        by = "Feature"]$V1)) )
    }
  }
}
rm(mle, fit_obj, sim_dt, dt, cpg, c, r)
```


```{r}
tmp <- copy(summary_stats) %>% .[, cpg_cov_round := round(cpg_cov)] %>%
  .[, c("cells", "cpg_cov_round", "epsilon_sd", "gamma_sd")] %>%
  setnames(c("Cells", "CpGs", "epsilon_sd", "gamma_sd"))
tmp$Cells <- factor(tmp$Cells, levels = unique(tmp$Cells), 
                        labels = paste(unique(tmp$Cells), "cells"))
# tmp2 <- tmp[, mean(epsilon_sd > 0.45), by = c("cpg_cov_round", "cells")] %>%
#   setorder(cells, cpg_cov_round)
```


# Correlation between uncertainty in posterior estimates and CpGs as we increase cells
```{r, fig.width=5, fig.height=3.5}
gg <- ggplot(tmp) +
    geom_point(aes(y = epsilon_sd, x = CpGs, fill = "#E69F00"), 
               shape = 21, size = 1.2, alpha = 1, stroke = 0.2) +
    geom_abline(intercept = 0.5, slope = 0, color = "black", 
                  linetype = "dashed", alpha = 0.7) +
    facet_wrap(~Cells, scales = "free_x", nrow = 1) +
    labs(x = "Number of CpGs", 
         y = expression(paste("Std of posterior estimates ", epsilon))) +
    theme_classic() +
    scale_fill_manual(values = "#E69F00") +
    theme(
        legend.position = "none",
        legend.title = element_blank(),
        legend.margin = margin(-2, 0, -2, 0),
        legend.box.margin = margin(-2, 0, -2, 0),
        panel.spacing.x = unit(0.9, "lines"),
        plot.tag = element_text(color = "black", face = "bold", size = rel(1.6)),
        legend.text = element_text(color = "black", size = rel(1.1)),
        strip.text = element_text(color = "black", size = rel(1.1)),
        axis.text = element_text(color = "black", size = rel(0.8)),
        axis.title = element_text(color = "black", size = rel(1.1))
      )
gg
pdf(sprintf("%s/robustness_estimates.pdf", out_dir), width = 6, height = 4)
print(gg)
dev.off()
```
