---
title: "scMET scalability on running windows"
author: "C.A.Kapourani & R. Argelaguet"
output: 
  html_notebook:
    df_print: paged
    highlight: haddock
    number_sections: yes
    theme: cerulean
    toc: yes
---

# Load libraries and settings
```{r}
suppressPackageStartupMessages(library(scMET))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(ggpubr))

## I/O
source("../load_settings.R")
out_dir <- "~/datasets/scMET_ms/ecker2017/scalability/"
if (!dir.exists(out_dir)) { dir.create(out_dir, recursive = TRUE) }
```

# Running times
Taken from logs of scMET. Should automate this, for now adding running times, manually.
```{r}
# In hours
size_10k_all_cells <- c(30, 33, 23, 30, 31, 29, 32, 27, 28, 24, 33, 24, 28, 21, 18, 19, 23, 23, 13, 8)
size_20k_all_cells <- c(31, 32, 24, 25, 27, 32, 32, 28, 24, 27, 31, 20, 30, 21, 19, 18, 16, 21, 12, 10)
size_10k_inh       <- c(7, 5, 4, 6, 5, 5, 8, 4, 4, 4, 5, 4, 4, 5, 5, 5, 4, 3, 3, 2)

df <- data.frame(feature_set = c(rep("Window 10k - All cells", 20), 
                        rep("Window 20k - All cells", 20), 
                        rep("Window 10k - Inhibitory cells", 20)),
           hours = c(size_10k_all_cells, size_20k_all_cells, size_10k_inh))
```


## Scalability plots
```{r}
pdf(sprintf("%s/scalability_ecker_window.pdf", out_dir), width = 7, height = 4)
ggboxplot(df, x =  "feature_set", y = "hours", ylab = "Time in hours", 
          xlab = "", fill = "cornflowerblue") #+
  #coord_cartesian(ylim = c(0, 2500))
dev.off()
```
